### ISSUE TITLE
Visitor Tracking in New Notebook

### ISSUE THREAD

**Issue by afiaka87** [EleutherAI/vqgan-clip#1]
Please don't do this sort of tracking in open source notebooks. I immediately had to check every URL in the jupyter notebook after I realized this. 

edit: certainly worth reading the details of the tracking before jumping to any conclusions.

**Comment by afiaka87** [comment]
@neverix

**Comment by StellaAthena** [comment]
@afiaka87 Thank you for raising your concern. Can you explain what the issue is precisely?

Is it the badge at the top of the notebook that says “Visitors [number]”? Why does the presence of that counter upset you? It doesn’t track you or do anything bad to your system. In fact, badges like that one are widely used in open source coding projects such as [DeepSpeed](https://github.com/microsoft/DeepSpeed).

**Comment by afiaka87** [comment]
@StellaAthena bet - thanks for addressing my concerns.

Indeed - I was not aware this was common practice; I suppose I just wasn't expecting it and overreacted a bit? My primary concern was simply that the domain used for visitor counting was owned by the creator of the notebook (for instance) and thus could be used for IP tracking. I am aware that this type of tracking has existed since before MySpace - I just didn't expect to find it in this particular development workflow (until now) from this particular organization (which happens to be highly decentralized and largely based on the internet - a good reason to practice decent Op Sec).

I suppose I ultimately don't really mind. Not something I would personally do and I'll probably be clicking the GitHub links instead of the colab ones from here on out, but it's rather subjective I guess. 

Do you mind if I ask why there is a need to track the number of visitors a notebook gets? I guess it's okay to say "popularity contest", because I can't really see a reason why that info is substantially more useful than say, GitHub stars, 👍 on Discord, etc.

**Comment by afiaka87** [comment]
> It doesn’t track you

Could you clarify this point? Is it not more or less using the same image-tracking technique that advertisers are known for using to see if you have opened an email (for instance)?

**Comment by StellaAthena** [comment]
@afiaka87

> Indeed - I was not aware this was common practice; I suppose I just wasn't expecting it and overreacted a bit? My primary concern was simply that the domain used for visitor counting was owned by the creator of the notebook (for instance) and thus could be used for IP tracking. I am aware that this type of tracking has existed since before MySpace - I just didn't expect to find it in this particular development workflow (until now) from this particular organization (which happens to be highly decentralized and largely based on the internet - a good reason to practice decent Op Sec).

You can find the code that underlies the counter [here](https://github.com/jwenjian/visitor-badge/blob/master/main.py). What it does is increment a counter every time the page is loaded. The counter is stored on a server, but no information about you is collected or stored. You can personally verify that this is the case.

> I suppose I ultimately don't really mind. Not something I would personally do and I'll probably be clicking the GitHub links instead of the colab ones from here on out, but it's rather subjective I guess.

Why? What are you afraid of?

> Do you mind if I ask why there is a need to track the number of visitors a notebook gets? I guess it's okay to say "popularity contest", because I can't really see a reason why that info is substantially more useful than say, GitHub stars, 👍 on Discord, etc.

I don't know why @neverix chose to put it in, it was not something we discussed.

**Comment by afiaka87** [comment]
ah gotcha. 

> Why? What are you afraid of?

It's rather subjective. I suspect you disagree with my takes on it based on your disposition.

But, just the stuff I mentioned. Having my IP tracked. It still ultimately is; and I believe we're merely working with different definitions of "tracked" - one where you assume good faith on part of the sitemaster of "countAPI" and one where I assume "countAPI" got hacked a week ago. It's like a personality trait of mine - not an outright dismissal of your argument.

**Comment by StellaAthena** [comment]
> But, just the stuff I mentioned. Having my IP tracked. It still ultimately is; and I believe we're merely working with different definitions of "tracked" - one where you assume good faith on part of the sitemaster of "countAPI" and one where I assume "countAPI" got hacked a week ago. It's like a personality trait of mine - not an outright dismissal of your argument.

Colab notebooks are run on a remote server. I don't understand why you think your IP address is even involved at all. If you want to be certain you can monitor the outbound traffic, but I'm not sure what to tell you other than the notebook doesn't do what you fear and you can personally verify that fact for yourself.
