### ISSUE TITLE
Error executing main,py

### ISSUE THREAD

**Issue by NapalmCandy** [EleutherAI/vqgan-clip#10]
Hi,

I cloned the code, installed dependencies (without errors) do the checkpoints but when I run `python3.10 main.py -p "A painting of an apple in a fruit bowl"` it give me the error:

`(base) napalm@napalm-Z490-UD:~/Documentos/vqgan-clip-main$ python3.10 main.py -p "A painting of an apple in a fruit bowl"
Traceback (most recent call last):
  File "/home/napalm/Documentos/vqgan-clip-main/main.py", line 5, in <module>
    from vqgan_clip.grad import *
  File "/home/napalm/Documentos/vqgan-clip-main/vqgan_clip/grad.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
`

I tried to uninstall and reinstall every torch dependency. I am very noob on python, can you help me?

**Comment by NapalmCandy** [comment]
Solved.. it works with python3, but not python3.10

**Comment by tnwei** [comment]
Seeing the `(base)` prefix in your terminal output, looks like you ran `pip install` using Python in the conda `(base)` env. You previously called the script using `python3.10`, which is not the same Python interpreter, but a different Python installed on your system. You can check this by running `which python3` and `which python3.10`, they most likely point to different Python interpreters. 

When a conda env is active, `python` and `python3` are symlinked to the relevant Python in the activated conda env.

**Comment by atigm** [comment]
I have the same problem, what version of python do you use (3.?) ?
What's version required for this project?

Error when I execute command `python main.py -p "A painting of an apple in a fruit bowl"` :
```
Traceback (most recent call last):
  File "/Users/.../vqgan-clip-main/main.py", line 246, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "/Users/.../vqgan-clip-main/main.py", line 164, in load_vqgan_model
    model = vqgan.VQModel(**config.model.params)
.....
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
```
