### ISSUE TITLE
Can't Find VQGAN_Gumbel Model

### ISSUE THREAD

**Issue by realchangnesia** [EleutherAI/vqgan-clip#5]
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-bd52c5eb0c1e> in <module>()
     12 cut_out_num=64
     13 
---> 14 model = load_vqgan_model('vqgan_gumbel_f8_8192.yaml', 'vqgan_gumbel_f8_8192.ckpt').to(device)
     15 
     16 perceptor, preprocess = clip.load(clip_model, jit=False)

Sorry if there's an obvious solution for this I'm missing, but I can't figure out how to get the vqgan_gumbel models

**Comment by StellaAthena** [comment]
Well where did you save the model to? Are you loading from the location of the checkpoint?
